src/scheduler/model/algorithm/CouldNotBeScheduledException.java
src/scheduler/model/algorithm/CourseAvailList.java
src/scheduler/model/algorithm/CourseDayAvail.java
src/scheduler/model/algorithm/CourseOverlapTracker.java
src/scheduler/model/algorithm/CourseWeekAvail.java
src/scheduler/model/algorithm/DayAvail.java
src/scheduler/model/algorithm/DaysAndTime.java
src/scheduler/model/algorithm/DaysForClasses.java
src/scheduler/model/algorithm/EndBeforeStartException.java
src/scheduler/model/algorithm/GenAvail.java
src/scheduler/model/algorithm/Generate.java
src/scheduler/model/algorithm/GenWeekAvail.java
src/scheduler/model/algorithm/InstructorCanTeachNothingException.java
src/scheduler/model/algorithm/InstructorDecorator.java
src/scheduler/model/algorithm/InstructorWTUMaxedException.java
src/scheduler/model/algorithm/LocationDecorator.java
src/scheduler/model/algorithm/NoClassOverlap.java
src/scheduler/model/algorithm/PreferenceExistsException.java
src/scheduler/model/algorithm/Preferences.java
src/scheduler/model/algorithm/ScheduleDecorator.java
src/scheduler/model/algorithm/ScheduleItemDecorator.java
src/scheduler/model/algorithm/SchedulePreference.java
src/scheduler/model/algorithm/SectionTracker.java
src/scheduler/model/algorithm/SiMap.java
src/scheduler/model/algorithm/Staff.java
src/scheduler/model/algorithm/TimeRange.java
src/scheduler/model/algorithm/Week.java
src/scheduler/model/algorithm/WeekAvail.java
src/scheduler/model/Course.java
src/scheduler/model/CSVExporter.java
src/scheduler/model/CSVImporter.java
src/scheduler/model/CSVStructure.java
src/scheduler/model/Day.java
src/scheduler/model/db/DatabaseException.java
src/scheduler/model/db/IDatabase.java
src/scheduler/model/db/IDBCourse.java
src/scheduler/model/db/IDBCourseAssociation.java
src/scheduler/model/db/IDBCoursePreference.java
src/scheduler/model/db/IDBDayPattern.java
src/scheduler/model/db/IDBDocument.java
src/scheduler/model/db/IDBEquipmentType.java
src/scheduler/model/db/IDBInstructor.java
src/scheduler/model/db/IDBLocation.java
src/scheduler/model/db/IDBObject.java
src/scheduler/model/db/IDBOfferedDayPattern.java
src/scheduler/model/db/IDBProvidedEquipment.java
src/scheduler/model/db/IDBSchedule.java
src/scheduler/model/db/IDBScheduleItem.java
src/scheduler/model/db/IDBTime.java
src/scheduler/model/db/IDBTimePreference.java
src/scheduler/model/db/IDBUsedEquipment.java
src/scheduler/model/db/IDBUser.java
src/scheduler/model/db/simple/Database.java
src/scheduler/model/db/simple/DBCourse.java
src/scheduler/model/db/simple/DBCourseAssociation.java
src/scheduler/model/db/simple/DBCoursePreference.java
src/scheduler/model/db/simple/DBDayPattern.java
src/scheduler/model/db/simple/DBDocument.java
src/scheduler/model/db/simple/DBEquipmentType.java
src/scheduler/model/db/simple/DBInstructor.java
src/scheduler/model/db/simple/DBLocation.java
src/scheduler/model/db/simple/DBObject.java
src/scheduler/model/db/simple/DBOfferedDayPattern.java
src/scheduler/model/db/simple/DBProvidedEquipment.java
src/scheduler/model/db/simple/DBSchedule.java
src/scheduler/model/db/simple/DBScheduleItem.java
src/scheduler/model/db/simple/DBTime.java
src/scheduler/model/db/simple/DBTimePreference.java
src/scheduler/model/db/simple/DBUsedEquipment.java
src/scheduler/model/db/simple/DBUser.java
src/scheduler/model/db/sqlite/SQLCourse.java
src/scheduler/model/db/sqlite/SQLdb.java
src/scheduler/model/db/sqlite/SQLDocument.java
src/scheduler/model/db/sqlite/SQLInstructor.java
src/scheduler/model/db/sqlite/SQLLocation.java
src/scheduler/model/db/sqlite/SQLObject.java
src/scheduler/model/db/sqlite/SQLScheduleItem.java
src/scheduler/model/db/sqlite/SQLUser.java
src/scheduler/model/Document.java
src/scheduler/model/Identified.java
src/scheduler/model/Instructor.java
src/scheduler/model/Location.java
src/scheduler/model/Model.java
src/scheduler/model/Schedule.java
src/scheduler/model/ScheduleItem.java
src/scheduler/model/tempalgorithm/GenerationAlgorithm.java
src/scheduler/model/User.java
src/scheduler/view/web/client/calendar/CalendarListView.java
src/scheduler/view/web/client/calendar/CalendarTableView.java
src/scheduler/view/web/client/calendar/CourseListView.java
src/scheduler/view/web/client/calendar/DOMUtility.java
src/scheduler/view/web/client/calendar/DragAndDropController.java
src/scheduler/view/web/client/calendar/DummySchedule.java
src/scheduler/view/web/client/calendar/EditScheduleItemDlg.java
src/scheduler/view/web/client/calendar/ScheduleEditWidget.java
src/scheduler/view/web/client/DocumentTabOpener.java
src/scheduler/view/web/client/ExportDialog.java
src/scheduler/view/web/client/GreetingService.java
src/scheduler/view/web/client/GreetingServiceAsync.java
src/scheduler/view/web/client/HTMLUtilities.java
src/scheduler/view/web/client/Import.java
src/scheduler/view/web/client/InvalidLoginException.java
src/scheduler/view/web/client/IViewContents.java
src/scheduler/view/web/client/Login.java
src/scheduler/view/web/client/MergeDialog.java
src/scheduler/view/web/client/NewScheduleCreator.java
src/scheduler/view/web/client/SaveAsDialog.java
src/scheduler/view/web/client/schedule/CourseListItem.java
src/scheduler/view/web/client/schedule/FiltersViewWidget.java
src/scheduler/view/web/client/schedule/ReschedulePopup.java
src/scheduler/view/web/client/schedule/ScheduleItemHTML.java
src/scheduler/view/web/client/Scheduler.java
src/scheduler/view/web/client/table/columns/ButtonColumn.java
src/scheduler/view/web/client/table/columns/ConstantStringColumn.java
src/scheduler/view/web/client/table/columns/DeleteCell.java
src/scheduler/view/web/client/table/columns/DeleteColumn.java
src/scheduler/view/web/client/table/columns/EditButtonColumn.java
src/scheduler/view/web/client/table/columns/EditingCheckboxCell.java
src/scheduler/view/web/client/table/columns/EditingCheckboxColumn.java
src/scheduler/view/web/client/table/columns/EditingMultiselectCell.java
src/scheduler/view/web/client/table/columns/EditingMultiselectColumn.java
src/scheduler/view/web/client/table/columns/EditingSelectCell.java
src/scheduler/view/web/client/table/columns/EditingSelectColumn.java
src/scheduler/view/web/client/table/columns/EditingStringCell.java
src/scheduler/view/web/client/table/columns/EditingStringColumn.java
src/scheduler/view/web/client/table/columns/ReadingStringCell.java
src/scheduler/view/web/client/table/columns/ReadingStringColumn.java
src/scheduler/view/web/client/table/columns/StringColumn.java
src/scheduler/view/web/client/table/IFactory.java
src/scheduler/view/web/client/table/IGetter.java
src/scheduler/view/web/client/table/ISetter.java
src/scheduler/view/web/client/table/IStaticGetter.java
src/scheduler/view/web/client/table/IStaticSetter.java
src/scheduler/view/web/client/table/IStaticValidator.java
src/scheduler/view/web/client/table/MemberIntegerComparator.java
src/scheduler/view/web/client/table/MemberStringComparator.java
src/scheduler/view/web/client/table/OsmTable.java
src/scheduler/view/web/client/table/ResizeableWidget.java
src/scheduler/view/web/client/table/SortWidget.java
src/scheduler/view/web/client/table/validators/StaticDecimalValidator.java
src/scheduler/view/web/client/table/validators/StaticNumberValidator.java
src/scheduler/view/web/client/UpdateHeaderStrategy.java
src/scheduler/view/web/client/View.java
src/scheduler/view/web/client/ViewFrame.java
src/scheduler/view/web/client/views/AdminConfigView.java
src/scheduler/view/web/client/views/AdminScheduleNavView.java
src/scheduler/view/web/client/views/CalendarView.java
src/scheduler/view/web/client/views/LoadingPopup.java
src/scheduler/view/web/client/views/LoginView.java
src/scheduler/view/web/client/views/resources/courses/CoursesDataSource.java
src/scheduler/view/web/client/views/resources/courses/CoursesView.java
src/scheduler/view/web/client/views/resources/instructors/InstructorPreferencesView.java
src/scheduler/view/web/client/views/resources/instructors/InstructorsDataSource.java
src/scheduler/view/web/client/views/resources/instructors/InstructorsView.java
src/scheduler/view/web/client/views/resources/instructors/InstructorTimePreferencesWidget.java
src/scheduler/view/web/client/views/resources/instructors/NoCourseDialog.java
src/scheduler/view/web/client/views/resources/locations/LocationsDataSource.java
src/scheduler/view/web/client/views/resources/locations/LocationsView.java
src/scheduler/view/web/client/views/ScheduleTrashView.java
src/scheduler/view/web/client/views/SelectScheduleView.java
src/scheduler/view/web/client/views/WindowHandler.java
src/scheduler/view/web/server/Conversion.java
src/scheduler/view/web/server/CSVDownload.java
src/scheduler/view/web/server/GreetingServiceImpl.java
src/scheduler/view/web/server/UploadService.java
src/scheduler/view/web/shared/CouldNotBeScheduledExceptionGWT.java
src/scheduler/view/web/shared/CourseGWT.java
src/scheduler/view/web/shared/DayCombinationGWT.java
src/scheduler/view/web/shared/DayGWT.java
src/scheduler/view/web/shared/DocumentGWT.java
src/scheduler/view/web/shared/Identified.java
src/scheduler/view/web/shared/InstructorGWT.java
src/scheduler/view/web/shared/LocationGWT.java
src/scheduler/view/web/shared/OldScheduleItemGWT.java
src/scheduler/view/web/shared/Pair.java
src/scheduler/view/web/shared/ScheduleItemGWT.java
src/scheduler/view/web/shared/ScheduleItemList.java
src/scheduler/view/web/shared/UserDataGWT.java
test/scheduler/model/AlgorithmStressTest.java
test/scheduler/model/AlgorithmTest.java
test/scheduler/model/AlgorithmTestSimpleDB.java
test/scheduler/model/AlgorithmTestTwo.java
test/scheduler/model/CoursesTest.java
test/scheduler/model/CoursesTestSimpleDB.java
test/scheduler/model/CSVTest.java
test/scheduler/model/db/DatabaseTest.java
test/scheduler/model/db/DatabaseTestCase.java
test/scheduler/model/db/DatabaseTestSimpleDB.java
test/scheduler/model/DocumentsTest.java
test/scheduler/model/DocumentsTestSimpleDB.java
test/scheduler/model/DocumentsTestSQLDB.java
test/scheduler/model/InstructorsPreferencesTest.java
test/scheduler/model/InstructorsPreferencesTestSimpleDB.java
test/scheduler/model/InstructorsTest.java
test/scheduler/model/InstructorsTestSimpleDB.java
test/scheduler/model/InstructorsTestSQLDB.java
test/scheduler/model/LocationsTest.java
test/scheduler/model/LocationsTestSimpleDB.java
test/scheduler/model/MiscModelTest.java
test/scheduler/model/ModelTestCase.java
test/scheduler/model/ModelTestUtility.java
test/scheduler/model/SampleTestSuite.java
test/scheduler/model/ScheduleItemsTest.java
test/scheduler/model/ScheduleItemsTestSimpleDB.java
test/scheduler/model/tempalgorithm/TempAlgorithmTest.java
test/scheduler/model/tempalgorithm/TempAlgorithmTestSimpleDB.java
test/scheduler/model/UsersTest.java
test/scheduler/model/UsersTestSimpleDB.java
test/scheduler/view/web/shared/AlgorithmRandDataTest.java
test/scheduler/view/web/shared/AlgorithmTest.java
test/scheduler/view/web/shared/BasicSelectSchedule.java
test/scheduler/view/web/shared/CreateScheduleTest.java
test/scheduler/view/web/shared/CSVTest.java
test/scheduler/view/web/shared/DefaultSelTestCase.java
test/scheduler/view/web/shared/LoginTest.java
test/scheduler/view/web/shared/PairTest.java
test/scheduler/view/web/shared/SampleTestSuite.java
test/scheduler/view/web/shared/Selenium/CalendarPage.java
test/scheduler/view/web/shared/Selenium/CoursesPage.java
test/scheduler/view/web/shared/Selenium/GeneratePage.java
test/scheduler/view/web/shared/Selenium/InstructorsPage.java
test/scheduler/view/web/shared/Selenium/LocationsPage.java
test/scheduler/view/web/shared/Selenium/LoginSelectPage.java
test/scheduler/view/web/shared/Selenium/SchedulerBot.java
test/scheduler/view/web/shared/Selenium/Toolbar.java
test/scheduler/view/web/shared/SmokeTestSuite.java
