/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddInstructor.java
 *
 * Created on Mar 5, 2010, 12:15:11 PM
 */
package scheduler.db.admin.admin_ui;

import scheduler.db.instructordb.*;
import scheduler.db.locationdb.*;
import scheduler.*;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author jsoliman
 */
public class AddLocalInstructor extends MyView {

    protected InstructorDB instructordb = Scheduler.idb;
    protected Instructor instructor = 
    new Instructor("", "", "", 0, null);
    //InstructorCoursePreferences icp = new InstructorCoursePreferences();

    /** Creates new form AddInstructor */
    public AddLocalInstructor() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * Initializes the window.
     */
    public void initialize() {
    	initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        NameLabel = new javax.swing.JLabel();
        IdLabel = new javax.swing.JLabel();
        WTULabel = new javax.swing.JLabel();
        OfficeLabel = new javax.swing.JLabel();
        DisabilitiesBox = new javax.swing.JCheckBox();
        TimePrefButton = new javax.swing.JButton();
        CoursePrefButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        NameField = new javax.swing.JTextField();
        IDField = new javax.swing.JTextField();
        WTUField = new javax.swing.JTextField();
        OfficeField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        LastNameFIeld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NameLabel.setText("First Name:");

        IdLabel.setText("ID:");

        WTULabel.setText("WTUs:");

        OfficeLabel.setText("Office #:");

        DisabilitiesBox.setText("Disabilities");
        DisabilitiesBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisabilitiesBoxActionPerformed(evt);
            }
        });

        TimePrefButton.setText("Time Preferences");
        TimePrefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimePrefButtonActionPerformed(evt);
            }
        });

        CoursePrefButton.setText("Course Preferences");
        CoursePrefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursePrefButtonActionPerformed(evt);
            }
        });


        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Last Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NameLabel)
                        .addGap(18, 18, 18)
                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DisabilitiesBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OfficeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OfficeField, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WTULabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WTUField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LastNameFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLabel)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LastNameFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdLabel)
                    .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WTULabel)
                    .addComponent(WTUField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OfficeLabel)
                    .addComponent(OfficeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(DisabilitiesBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitButton)
                    .addComponent(CancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void DisabilitiesBoxActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void TimePrefButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void CoursePrefButtonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        //icp.setVisible(true);
    }        

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
        this.setVisible(false);
    }                                            

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            String fName = NameField.getText();
            String lName = LastNameFIeld.getText();
            String id = IDField.getText();
            int wtu = Integer.parseInt(WTUField.getText());
            String office = OfficeField.getText(); 
            boolean disability = DisabilitiesBox.isSelected();
            instructor = new Instructor(fName, lName, id, wtu, parseOffice(office), disability);
            if (fName.equals("") || lName.equals("") || id.equals("")) {
                        JOptionPane.showMessageDialog(this,
                           "One of the fields is empty.",
                           "Error",
                           JOptionPane.ERROR_MESSAGE);  
            }
            else if (!office.contains("-") ) {
                        JOptionPane.showMessageDialog(this,
                           "Office must follow format [Building]-[Room].",
                           "Error",
                           JOptionPane.ERROR_MESSAGE);
            }
            else if (instructordb.getLocalData().contains(instructor)) {
                        JOptionPane.showMessageDialog(this,
                           "Instructor is already in the database",
                           "Error",
                           JOptionPane.ERROR_MESSAGE);            
            }
            else {
               instructordb.addLocalInstructor(instructor);
               this.setVisible(false);
            }
        }
        catch ( NumberFormatException e) {


            JOptionPane.showMessageDialog(this,
               "WTUs field must be an integer.",
               "Error",
               JOptionPane.ERROR_MESSAGE);

        }
    }                                            

    public Location parseOffice(String location) {
        StringTokenizer tokenizer = new StringTokenizer(location, "-");
        String building = tokenizer.nextToken().toString();
        String room = tokenizer.nextToken().toString();
        return new Location(building, room);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLocalInstructor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CoursePrefButton;
    private javax.swing.JCheckBox DisabilitiesBox;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JTextField LastNameFIeld;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField OfficeField;
    private javax.swing.JLabel OfficeLabel;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton TimePrefButton;
    private javax.swing.JTextField WTUField;
    private javax.swing.JLabel WTULabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration

}
