package scheduler.db.admin.admin_ui;

import javax.swing.*;

import edu.calpoly.csc.scheduler.Scheduler;
import edu.calpoly.csc.scheduler.model.db.idb.Instructor;
import edu.calpoly.csc.scheduler.model.db.idb.InstructorDB;
import edu.calpoly.csc.scheduler.model.db.ldb.Location;
import scheduler.*;
import scheduler.db.instructordb.*;

/**
 * This class allows the user to add, edit, and delete an instructor from the
 * database.
 * 
 * @author Cedric Wienold
 */
public class AddInstructor extends javax.swing.JFrame {

	/** Instructor Database */
	protected InstructorDB database = Scheduler.idb;
	
	/** Individual Instructor */
	private Instructor instructor = new Instructor("","","",0,null);
	
   /** */
   //private InstructorCoursePreferences icp =
   //new InstructorCoursePreferences();

    /** Creates new form AddCourse */
    public AddInstructor(InstructorDB db) {
    	this.database = db;
        initComponents();
        setTitle("Add an Instructor");
    }
    
    /**
     * Initializes the window.
     */
    public void initialize() {
    	initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        NameField = new javax.swing.JTextField();
        UserIDField = new javax.swing.JTextField();
        wtusField = new javax.swing.JTextField();
        OfficeBuildingField = new javax.swing.JTextField();
        FirstName = new javax.swing.JLabel();
        UserID = new javax.swing.JLabel();
        WTUs = new javax.swing.JLabel();
        OfficeBuilding = new javax.swing.JLabel();
        OfficeNumberField = new javax.swing.JTextField();
        OfficeNumber = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        LastName = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FirstName.setText("First Name");

        LastName.setText("Last Name");

        UserID.setText("User ID");

        WTUs.setText("WTUs");

        OfficeBuilding.setText("Office Building:");

        OfficeNumber.setText("Office Number:");

        OfficeNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OfficeNumberFieldActionPerformed(evt);
            }
        });

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstName)
                            .addComponent(LastName))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NameField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Submit)
                        .addGap(18, 18, 18)
                        .addComponent(Cancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserID)
                            .addComponent(WTUs)
                            .addComponent(OfficeBuilding)
                            .addComponent(OfficeNumber))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wtusField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UserIDField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(OfficeBuildingField, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(OfficeNumberField))))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wtusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WTUs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OfficeBuildingField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OfficeBuilding))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OfficeNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OfficeNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(Cancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
    }                                      

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            String fname = NameField.getText(); 
            String lname = LastName.getText();
            String uid = UserIDField.getText();
            int wtus = Integer.parseInt(wtusField.getText().trim());
            String bldg = OfficeBuildingField.getText();
            String room = OfficeNumberField.getText();
            instructor = new Instructor(fname,lname,uid,wtus,new Location(bldg,room));
            if (fname.equals("") || lname.equals("") || uid.equals("")) {
                        JOptionPane.showMessageDialog(this,
                           "One of the fields is empty.",
                           "Error",
                           JOptionPane.ERROR_MESSAGE);  
            }
            else {
                  database.addInstructor(instructor);
                  this.setVisible(false);
            }
        }
        catch ( NumberFormatException e) {


            JOptionPane.showMessageDialog(this,
               "WTUs field must be an integer.",
               "Error",
               JOptionPane.ERROR_MESSAGE);

        }
    }                                      

    private void CoursePrefButtonActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
    }

    private void OfficeNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AddInstructor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel OfficeBuilding;
    private javax.swing.JTextField OfficeBuildingField;
    private javax.swing.JLabel OfficeNumber;
    private javax.swing.JTextField OfficeNumberField;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel UserID;
    private javax.swing.JTextField UserIDField;
    private javax.swing.JLabel WTUs;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField wtusField;
    // End of variables declaration

}
