package scheduler.db.admin.admin_ui;

import java.util.*;

import javax.swing.*;

import edu.calpoly.csc.scheduler.Scheduler;
import edu.calpoly.csc.scheduler.model.db.cdb.Course;
import edu.calpoly.csc.scheduler.model.db.idb.Instructor;
import edu.calpoly.csc.scheduler.model.db.idb.InstructorDB;
import edu.calpoly.csc.scheduler.view.desktop.MyView;
import edu.calpoly.csc.scheduler.view.desktop.menu.schedule.ScheduleMenu;

import scheduler.*;
import scheduler.db.*;
import scheduler.db.instructordb.*;

/**
 * The View of the course database class.
 * @author Jan Lorenz Soliman
 */
public class InstructorView extends MyView implements Observer {

	/** Instructor Database */
	private InstructorDB database = Scheduler.idb;
	
	/** Current Instructor */
	private Instructor instructor;
	
	/** Window object for adding instructor */
	private AddInstructorAlt addInstructor;

	/** Creates new form LocationView */
	public InstructorView() {
        database.addObserver(this);
        addInstructor = new AddInstructorAlt();
		initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Instructor Database");
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		NameLabel = new javax.swing.JLabel();
		IDLabel = new javax.swing.JLabel();
		WTULabel = new javax.swing.JLabel();
		OfficeNumberLabel = new javax.swing.JLabel();
		AddButton = new javax.swing.JButton();
		EditButton = new javax.swing.JButton();
		RemoveButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		final ArrayList<String> names = new ArrayList<String>();
		Vector<Instructor> data = (Vector) database.getData();
		if (data != null) {
			for (Instructor i: data ) {
				names.add(i.getId());
			}
		}
		jList1.setModel(new javax.swing.AbstractListModel() {
			//String[] strings = { "CPE 101", "CPE 102", "CPE 103", "CPE 225" };
			ArrayList<String> strings = names;
			public int getSize() { return strings.size(); }
			public Object getElementAt(int i) { return strings.get(i); }
		});
		jScrollPane1.setViewportView(jList1);
//      jScrollPane1.getViewport().add(ScheduleMenu.cList);
		NameLabel.setText("Name: ");

		IDLabel.setText("ID:");

		WTULabel.setText("WTU:");

		OfficeNumberLabel.setText("Office Number:");

		AddButton.setText("Add Instructor");
		AddButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				AddButtonActionPerformed(evt);
			}
		});

		EditButton.setText("Edit Instructor");

		RemoveButton.setText("Remove Instructor");
		RemoveButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				RemoveButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(AddButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(EditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(RemoveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))	
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(NameLabel)
										.addComponent(IDLabel)
										.addComponent(WTULabel)
										.addComponent(OfficeNumberLabel))
										.addContainerGap(191, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(NameLabel)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(IDLabel)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(WTULabel)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(OfficeNumberLabel))
										.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(AddButton)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(EditButton)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(RemoveButton)
										.addContainerGap(29, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>

	public void update(Observable obs, Object obj) {
		database = Scheduler.idb;
		database.addObserver(this);
		System.out.println("In Update");
		//this.initComponents();


		NameLabel.setText("Name: ");
		IDLabel.setText("ID: ");
		WTULabel.setText("WTUs: ");
		OfficeNumberLabel.setText("Office Number: ");

		final ArrayList<String> names = new ArrayList<String>();
		Vector<Instructor> data = (Vector) database.getData();
		if (data != null) {
			for (Instructor i: data ) {
				names.add(i.getId());
			}
		}
		jList1.setModel(new javax.swing.AbstractListModel() {
			//String[] strings = { "CPE 101", "CPE 102", "CPE 103", "CPE 225" };
			ArrayList<String> strings = names;
			public int getSize() { return strings.size(); }
			public Object getElementAt(int i) { return strings.get(i); }
		});
		jScrollPane1.setViewportView(jList1);
	}

	private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
	   database.removeInstructor(instructor);	
	}                                        

	private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {                                         
		// TODO add your handling code here:
		addInstructor.initialize();
		addInstructor.setVisible(true);
        System.out.println("In InstructorViewView.AddButtonActionPerformed");
	}                                        

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new InstructorView().setVisible(true);
			}
		});
	}

	private void instructorListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_instructorListValueChanged
		if (!evt.getValueIsAdjusting()) {
			if (jList1.getSelectedValue() != null) {
				String selection = jList1.getSelectedValue().toString();
				instructor = database.getInstructor(selection);
				
				System.out.println("Instructor is " + instructor.getName());
				NameLabel.setText("First Name: " + instructor.getName());
				IDLabel.setText("ID: " + instructor.getId());
				WTULabel.setText("WTU: " + instructor.getMaxWTU());
				OfficeNumberLabel.setText("Office Number: " +
						instructor.getOffice().getBuilding() + "-"
						+ instructor.getOffice().getRoom());
			}

		}
	}//GEN-LAST:event_instructorListValueChanged


	// Variables declaration - do not modify
	private javax.swing.JButton AddButton;
	private javax.swing.JButton EditButton;
	private javax.swing.JLabel IDLabel;
	private javax.swing.JLabel NameLabel;
	private javax.swing.JLabel OfficeNumberLabel;
	private javax.swing.JButton RemoveButton;
	private javax.swing.JLabel WTULabel;
	private javax.swing.JList jList1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration

}
